# Generated by Django 4.0.3 on 2022-04-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descripton',
            new_name='description',
        ),
    ]
