# Generated by Django 4.0.3 on 2022-04-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='comment',
            name='recommended',
            field=models.BooleanField(default=True, verbose_name='توصیه می شود'),
        ),
    ]
